- name: 首页
  icon: fas fa-home
  id: home
  active: true
- name: 新闻
  icon: fas fa-newspaper
  id: news
- name: 互联网
  icon: fas fa-terminal
  id: net
- name: 工具
  icon: fas fa-toolbox
  id: tool
- name: 趣站
  icon: fas fa-face-smile
  id: fun 
